name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Download Node.js runtime for Linux and Windows
        run: |
          mkdir -p runtimes
          curl -o runtimes/node-linux.tar.gz https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.gz
          curl -o runtimes/node-windows.zip https://nodejs.org/dist/v22.14.0/node-v22.14.0-win-x64.zip

      - name: Package project with runtimes
        run: |
          mkdir -p node/22
          tar -xzvf runtimes/node-linux.tar.gz --strip-components=2 -C node/22 node-v22.14.0-linux-x64/bin/node
          unzip -j runtimes/node-windows.zip "*/node.exe" -d node/22

      - name: Install dependencies
        run: npm ci

      - name: Build and package project
        run: npm run dist

      - name: Run semantic-release
        id: semrel
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract release version
        run: echo "RELEASE_VERSION=$(npx semantic-release --dry-run | grep -oP '(?<=The next release version is ).*')" >> $GITHUB_ENV

      - name: Rename assets with version
        run: |
          mv jon2.0-linux.tar.gz jon2.0_${RELEASE_VERSION}-linux.tar.gz
          mv jon2.0-windows.zip jon2.0_${RELEASE_VERSION}-windows.zip

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            jon2.0_${RELEASE_VERSION}-linux.tar.gz
            jon2.0_${RELEASE_VERSION}-windows.zip
